# -*- coding: utf-8 -*-
"""Multimodal approach

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zckaNTSFBYt4Ge2EHPf-0FfBNJmaJc3Q
"""

pip install tensorflow pandas numpy scikit-learn matplotlib seaborn opencv-python

import numpy as np
import pandas as pd
import cv2
import os
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, classification_report, roc_curve, auc

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Input, Conv2D, MaxPooling2D, Flatten, Concatenate

!pip install shap

import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import cv2
import shap
from PIL import Image
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

clinical = pd.read_csv("/content/scrub_typhus_clinical_dataset_1000.csv")


clinical.head()

# Ensure column names are clean

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Clinical Model Accuracy:", accuracy_score(y_test, rf_pred))

from sklearn.svm import SVC

svc_model = SVC()

svc_model.fit(X_train, y_train)

svc_pred = svc_model.predict(X_test)

svc_accuracy = accuracy_score(y_test, svc_pred)

print("SVC Accuracy:", svc_accuracy)

explainer = shap.TreeExplainer(rf_model)
shap_values = explainer.shap_values(X_test)

# SHAP Summary Plot
shap.summary_plot(shap_values, X_test)

# SHAP Feature Importance
shap.summary_plot(shap_values, X_test, plot_type="bar")

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

import os

os.makedirs('/content/dataset/Scrub_Typhus', exist_ok=True)
os.makedirs('/content/dataset/Not_Scrub_Typhus', exist_ok=True)

from google.colab import files
uploaded = files.upload()

import os
import cv2
if 'uploaded' in locals() or 'uploaded' in globals():
    print(f"Processing {len(uploaded)} uploaded images...")
    for i, file_name in enumerate(uploaded.keys()):
        # The image path is simply the file_name as they are in the current directory
        img_path = file_name

        image = cv2.imread(img_path)

        if image is None:
            print(f"Warning: Could not read image '{file_name}'. Skipping.")
            continue

        # Create a unique save path using the original filename and an index
        base_name = os.path.splitext(file_name)[0] # Get filename without extension
        save_path = f"dataset/Scrub_Typhus/{base_name}_{i}.jpg"

        # Ensure the target directory exists (though previous cells should have created it)
        os.makedirs("dataset/Scrub_Typhus", exist_ok=True)

        cv2.imwrite(save_path, image)
        print(f"Successfully saved '{file_name}' to '{save_path}'")

    print("All processed images saved into dataset/Scrub_Typhus")
else:
    print("Error: The 'uploaded' variable was not found. Please ensure the 'files.upload()' cell (TK24Hk4XOJTj) was executed successfully.")

from google.colab import files
uploaded = files.upload()

import os
import cv2
if 'uploaded' in locals() or 'uploaded' in globals():
    print(f"Processing {len(uploaded)} uploaded images...")
    for i, file_name in enumerate(uploaded.keys()):
        # The image path is simply the file_name as they are in the current directory
        img_path = file_name

        image = cv2.imread(img_path)

        if image is None:
            print(f"Warning: Could not read image '{file_name}'. Skipping.")
            continue

        # Create a unique save path using the original filename and an index
        base_name = os.path.splitext(file_name)[0] # Get filename without extension
        save_path = f"dataset/Not_Scrub_Typhus/{base_name}_{i}.jpg"

        # Ensure the target directory exists (though previous cells should have created it)
        os.makedirs("dataset/Not_Scrub_Typhus", exist_ok=True)

        cv2.imwrite(save_path, image)
        print(f"Successfully saved '{file_name}' to '{save_path}'")

    print("All processed images saved into dataset/Not_Scrub_Typhus")
else:
    print("Error: The 'uploaded' variable was not found. Please ensure the 'files.upload()' cell (TK24Hk4XOJTj) was executed successfully.")

from torchvision import datasets
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

dataset = datasets.ImageFolder("/content/dataset", transform=transform)

train_loader = DataLoader(dataset, batch_size=8, shuffle=True)

import torch.optim as optim

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

epochs = 5

for epoch in range(epochs):

    for images, labels in train_loader:

        optimizer.zero_grad()

        outputs = model(images)

        loss = criterion(outputs, labels)

        loss.backward()

        optimizer.step()

    print("Epoch:", epoch, "Loss:", loss.item())

torch.save(model.state_dict(), "scrub_model.pth")

model.load_state_dict(torch.load("scrub_model.pth"))
model.eval()



class ScrubCNN(nn.Module):

    def __init__(self):
        super(ScrubCNN,self).__init__()

        self.cnn = torchvision.models.resnet18(pretrained=True)

        self.cnn.fc = nn.Sequential(
            nn.Linear(512,128),
            nn.ReLU(),
            nn.Linear(128,2)
        )

    def forward(self,x):
        return self.cnn(x)

model = ScrubCNN()
model.eval()

image = Image.open("/content/image7.webp").convert("RGB")
image = Image.open("/content/not_image2.jpg").convert("RGB")
image = Image.open("/content/Sign-and-Symptoms-of-Scrub-Typhus.jpg").convert("RGB")
image = Image.open("/content/imag1.jpeg").convert("RGB")

input_tensor = transform(image).unsqueeze(0)

output = model(input_tensor)

A = torch.argmax(output)

prediction = torch.argmax(output)

print("Image Prediction:", prediction.item())

prob = torch.softmax(output, dim=1)

print("Non Scrub Typhus Probability:", prob[0][0].item())
print("Scrub Typhus Probability:", prob[0][1].item())

from PIL import Image
import torch

def predict_image(image_path):

    # Load image
    image = Image.open(image_path).convert("RGB")

    # Preprocess image
    input_tensor = transform(image).unsqueeze(0)

    # Model prediction
    with torch.no_grad():
        output = model(input_tensor)

    prediction = torch.argmax(output, dim=1).item()

    prob = torch.softmax(output, dim=1)

    print("Image:", image_path)

    if prediction == 1:
        print("Prediction: Scrub Typhus Detected")
    else:
        print("Prediction: No Scrub Typhus")

    print("Non Scrub Typhus Probability:", prob[0][0].item())
    print("Scrub Typhus Probability:", prob[0][1].item())

    return prediction

predict_image("/content/Sign-and-Symptoms-of-Scrub-Typhus.jpg")

predict_image("/content/not_image2.jpg")

predict_image("/content/dataset/Not_Scrub_Typhus/not_Image1_4.jpg")

predict_image("/content/dataset/Scrub_Typhus/image4_4.jpg")

class GradCAM:

    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None

        target_layer.register_forward_hook(self.save_activation)
        target_layer.register_full_backward_hook(self.save_gradient)

    def save_activation(self, module, input, output):
        self.activations = output

    def save_gradient(self, module, grad_input, grad_output):
        self.gradients = grad_output[0]

    def generate(self, input_image, class_idx):

        output = self.model(input_image)
        self.model.zero_grad()

        loss = output[0, class_idx]
        loss.backward()

        gradients = self.gradients
        activations = self.activations

        weights = torch.mean(gradients, dim=(2,3))

        cam = torch.zeros(activations.shape[2:])

        for i, w in enumerate(weights[0]):
            cam += w * activations[0, i]

        cam = torch.relu(cam)
        cam = cam / torch.max(cam)

        return cam.detach().numpy()

target_layer = model.cnn.layer4

gradcam = GradCAM(model, target_layer)

cam = gradcam.generate(input_tensor, prediction)

heatmap = cv2.applyColorMap(np.uint8(255*cam), cv2.COLORMAP_JET)

img = cv2.imread("/content/dataset/Scrub_Typhus/Scrub typhus symptoms in detail_6.jpg") # Changed from /content/image5.jpg to /content/imag1.jpeg
img = cv2.resize(img,(224,224))

heatmap = cv2.resize(heatmap,(224,224))

result = heatmap * 0.4 + img

cv2.imwrite("gradcam_output.jpg", result)

result = cv2.cvtColor(result.astype('uint8'), cv2.COLOR_BGR2RGB)

plt.imshow(result)
plt.axis("off")
plt.title("Grad-CAM Visualization")
plt.show()

# Example clinical sample
clinical_sample = X_test.iloc[[0]]

clinical_prob = rf_model.predict_proba(clinical_sample)[0][1]

image_prob = prob[0][1].item()

# Multimodal fusion
final_prob = (clinical_prob + image_prob) / 2

if final_prob > 0.5:
    final_prediction = 1
else:
    final_prediction = 0

print("Clinical Probability:", clinical_prob)
print("Image Probability:", image_prob)
print("Final Multimodal Probability:", final_prob)
print("Final Multimodal Prediction:", final_prediction)

from sklearn.metrics import confusion_matrix, precision_score, recall_score
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, rf_pred)

print(cm)

plt.figure(figsize=(6,5))

sns.heatmap(cm,
            annot=True,
            fmt="d",
            cmap="Blues",
            xticklabels=["No Scrub Typhus","Scrub Typhus"],
            yticklabels=["No Scrub Typhus","Scrub Typhus"])

plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")

plt.show()

precision = precision_score(y_test, rf_pred)
recall = recall_score(y_test, rf_pred)

print("Precision:", precision)
print("Recall:", recall)

from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt

y_prob = rf_model.predict_proba(X_test)[:,1]

fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

print("AUC Score:", roc_auc)

plt.figure(figsize=(6,5))

plt.plot(fpr, tpr, color='blue', label='ROC curve (area = %0.2f)' % roc_auc)

plt.plot([0,1], [0,1], color='red', linestyle='--')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')

plt.title('ROC Curve for Scrub Typhus Classification')

plt.legend(loc="lower right")

*plt.show()

